name = "BinderPlots"
uuid = "5e41213d-62ae-4ae0-a5b0-867e743d03c0"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "1.0.9"

[deps]
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"

[weakdeps]
"CalculusWithJulia" = "a2e0e22d-7d4c-5312-9169-8b992201a882"
"SimpleExpressions" = "deba94f7-f32a-40ad-b45e-be020a5ded2f"

[extensions]
BinderPlotsCalculusWithJuliaExt = "CalculusWithJulia"
BinderPlotsSimpleExpressionsExt = "SimpleExpressions"

[compat]
PlotUtils = "1"
PlotlyLight = "0.8"
CalculusWithJulia = "0.2"
SimpleExpressions = "1"
julia = "1.9"

[extras]
CalculusWithJulia = "a2e0e22d-7d4c-5312-9169-8b992201a882"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
