name = "BinderPlots"
uuid = "5e41213d-62ae-4ae0-a5b0-867e743d03c0"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "1.0.5"

[deps]
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"

[compat]
PlotUtils = "1"
PlotlyLight = "0.8"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
