name = "BinderPlots"
uuid = "5e41213d-62ae-4ae0-a5b0-867e743d03c0"
authors = ["jverzani <jverzani@gmail.com> and contributors"]
version = "1.0.15"

[deps]
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"

[weakdeps]
CalculusWithJulia = "a2e0e22d-7d4c-5312-9169-8b992201a882"
SimpleExpressions = "deba94f7-f32a-40ad-b45e-be020a5ded2f"
SymPyCore = "458b697b-88f0-4a86-b56b-78b75cfb3531"

[extensions]
BinderPlotsCalculusWithJuliaExt = "CalculusWithJulia"
BinderPlotsSimpleExpressionsExt = "SimpleExpressions"
BinderPlotsSymPyCoreExt = "SymPyCore"

[compat]
CalculusWithJulia = "0.2"
PlotUtils = "1"
PlotlyLight = "0.8, 0.9, 0.10, 0.11"
SimpleExpressions = "1"
SplitApplyCombine = "1"
SymPyCore = "0.2"
julia = "1.9"

[extras]
CalculusWithJulia = "a2e0e22d-7d4c-5312-9169-8b992201a882"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
